apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  type: LoadBalancer
  selector:
    app: goserver
  ports:
    - name: http
      port: 80 # Default port for image
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 80
      protocol: TCP